name: Enhancement Request
description: Request an enhancement to an existing feature
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: Description
      description: Describe the enhancement at a high-level.
    validations:
      required: true
  - type: input
    attributes:
      label: Discussion
      description: |
        If there has been a discussion around the enhancement, provide a wiki link to the discussion.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Motivation/Use Case
      description: Describe why the feature should be added. What problem does it solve?
    validations:
      required: false
  - type: textarea
    attributes:
      label: Details
      description: More details? Implementation ideas? Anything that will give us more context about the enhancement you are proposing!
    validations:
      required: false
